defaults: &defaults
  legal_entity: 'the University of Edinburgh, University of Glasgow and the University of California'

	# Warning: The abbreviation here should match the org.abbreviation value registered in your database!
  organisation:
    name: 'Digital Curation Center and University of California Curation Center'
    abbreviation: 'DCC'
    url: 'https://github.com/DMPRoadmap/roadmap/wiki'
    copywrite_name: 'DCC and UC3'
    email: 'dmponline@dcc.ac.uk'

  application:
    name: 'DMPRoadmap'
    url: 'https://github.com/DMPRoadmap/roadmap'
    version: '0.1.0'
    release_notes_url: 'https://github.com/DMPRoadmap/roadmap/wiki/Releases'
    issue_list_url: 'https://github.com/DMPRoadmap/roadmap/issues'
    user_group_subscription_url: 'http://listserv.ucop.edu/cgi-bin/wa.exe?SUBED1=ROADMAP-L&A=1'

development:
  <<: *defaults
    
test:
  <<: *defaults

staging:
  <<: *defaults
    
production:
  <<: *defaults
